# Generated by Django 5.0.3 on 2024-05-04 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('transaction_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('senior_citizen_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_transaction_limit', models.IntegerField()),
                ('atm_withdrawal_limit', models.IntegerField()),
                ('additional_atm_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('debit_card_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('debit_card_yearly_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('saving', 'Saving Account'), ('current', 'Current Account')], max_length=20)),
                ('account_subtype', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=11, unique=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bank_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=14, unique=True)),
                ('debit_card_number', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('account_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='applied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounttype')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
            ],
        ),
    ]
