# Generated by Django 5.0.3 on 2024-05-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_status_alter_branch_bank_manager_bankstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('active', 'Active')], default='applied', max_length=20),
        ),
    ]
