# Generated by Django 5.0.3 on 2024-05-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='variant',
        ),
    ]
