# Generated by Django 5.0.3 on 2024-05-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_accounttype_name_remove_accounttype_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='debit_card_fee',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='free_atm_withdrawals',
            field=models.IntegerField(default=0),
        ),
    ]
