# Generated by Django 5.0.3 on 2024-05-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_accounttype_debit_card_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='transaction_limit',
        ),
    ]
