# Generated by Django 5.0.3 on 2024-05-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_accounttype_transaction_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='free_atm_withdrawals',
            field=models.IntegerField(),
        ),
    ]
