# Generated by Django 5.0.3 on 2024-05-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='account_subtype',
            field=models.CharField(choices=[('saving-standard', 'Standard Saving Account'), ('saving-premium', 'Premium Saving Account'), ('current-standard', 'Standard Current Account'), ('current-premium', 'Premium Current Account')], max_length=20),
        ),
    ]
