# Generated by Django 5.0.3 on 2024-05-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_deposit_userdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeposit',
            name='deposit_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userdeposit',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
