# Generated by Django 5.0.3 on 2024-05-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_userdeposit_deposit_number_userdeposit_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeposit',
            old_name='deposit',
            new_name='deposit_type',
        ),
    ]
