# Generated by Django 5.0.3 on 2024-05-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='total_expenses',
            new_name='remaining_budget',
        ),
    ]
