# Generated by Django 5.0.3 on 2024-04-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_user_type_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin'), ('customer', 'Customer')], max_length=20),
        ),
    ]
