# Generated by Django 5.0.3 on 2024-05-10 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_customstokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='customstokens',
            name='access_token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 4, 33, 9, 577678, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='customstokens',
            name='refresh_token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 4, 3, 9, 577678, tzinfo=datetime.timezone.utc)),
        ),
    ]
