# Generated by Django 5.0.3 on 2024-05-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan_account_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
