# Generated by Django 5.0.3 on 2024-05-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanapplication_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
