# Generated by Django 5.0.3 on 2024-05-08 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_account_status'),
        ('loans', '0006_alter_loanapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='branch_id',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='branch',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch'),
        ),
    ]
