# Generated by Django 5.0.3 on 2024-05-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_remove_loanapplication_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
