# Generated by Django 5.0.3 on 2024-05-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_account_status'),
        ('transactions', '0002_transaction_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='destination_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_transactions', to='accounts.account'),
        ),
    ]
