# Generated by Django 5.0.3 on 2024-05-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_destination_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='destination',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
