# Generated by Django 5.0.3 on 2024-05-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destination_account_number',
            field=models.CharField(max_length=255),
        ),
    ]
