# Generated by Django 5.0.3 on 2024-05-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('loan_repayment', 'Loan Repayment'), ('processing_fee', 'Processing Fee'), ('loan sactioned', 'Loan Sactioned')], max_length=20),
        ),
    ]
